### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ysimonson** [ysimonson/binlog#8]
For now windows support is disabled, but it should be fairly straight-forward to add:

1) Link sqlite

2) Add windows releases to the maturin github workflow:

```
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist --cargo-extra-args="--all-features"
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
```
